// Rendering the thin caller workflows, and re-pinning the ones already there.
//
// The caller is the one generated artifact a consumer legitimately EDITS: the `with:`
// inputs are their toolchain (Ruby on or off, system packages, node version), and the
// `if:` guard is their access policy. So the two operations here are deliberately
// asymmetric — `render` produces a whole file for a repo that has none, and `repin`
// touches a single `@ref` on a file that already exists and leaves every other line
// alone. Nothing regenerates a caller in place; `sync` reports drift instead
// (see plan.mts).

import type { CallerSpec, Verb } from "./catalog.mts";
import { callersFor } from "./catalog.mts";

export interface CallerOptions {
  // The central repo the callers `uses:` — an owner/name slug, so a fork can install
  // its own copy of the workflows without editing the generated files.
  readonly workflowsRepo: string;
  // The git ref to pin: a moving major tag (`v1`), `main`, or an exact tag/SHA.
  readonly ref: string;
  // Toolchain: Ruby/Postgres/Redis for a Rails repo, off for everything else (ADR-0002).
  readonly enableRuby: boolean;
  // The identity the workflow commits as.
  readonly gitAuthorEmail: string;
  // A public repo gates its `pull_request_target` callers by author association: that
  // event runs PR-head code WITH secrets, so an ungated caller on a public repo lets
  // any external PR start a billed run against your credentials.
  readonly publicRepo: boolean;
}

// The `uses:` line's value — also what `repin` matches on, so the two cannot drift.
export function usesRef(caller: CallerSpec, repo: string, ref: string): string {
  return `${repo}/.github/workflows/${caller.workflow}@${ref}`;
}

function onBlock(caller: CallerSpec): readonly string[] {
  switch (caller.trigger) {
    case "issue-label":
      return ["on:", "  workflow_dispatch:", "  issues:", "    types: [labeled]"];
    case "pr-target-label":
      return ["on:", "  workflow_dispatch:", "  pull_request_target:", "    types: [labeled]"];
    case "pr-merge":
      // No `workflow_dispatch`: advance reads the merged PR out of the event payload,
      // so a manual run would have nothing to act on.
      return ["on:", "  pull_request:", "    types: [closed]"];
  }
}

// The job's `if:` guard. Three shapes, matching the three triggers.
function ifGuard(caller: CallerSpec, publicRepo: boolean): readonly string[] {
  if (caller.trigger === "pr-merge") {
    return [
      "    # Only a merged tracer-bullet PR into a spec branch. The final spec→default PR",
      "    # has base == default branch, so it does NOT match and does NOT re-trigger.",
      "    if: >-",
      "      github.event.pull_request.merged == true",
      "      && startsWith(github.event.pull_request.base.ref, 'agent/spec-')",
    ];
  }

  const label = caller.label;
  const dispatched = "github.event_name == 'workflow_dispatch'";
  const labelled = `github.event.label.name == '${label}'`;

  if (caller.trigger === "pr-target-label" && publicRepo) {
    return [
      "    # pull_request_target runs PR-head code with secrets; on this public repo,",
      "    # gate to internal authors so an external PR can never trigger the run.",
      "    if: >-",
      `      (${dispatched} || ${labelled})`,
      `      && (${dispatched}`,
      "          || contains(fromJSON('[\"OWNER\",\"MEMBER\",\"COLLABORATOR\"]'), github.event.pull_request.author_association))",
    ];
  }

  return [`    if: ${dispatched} || ${labelled}`];
}

// One caller file, ready to write.
export function renderCaller(caller: CallerSpec, options: CallerOptions): string {
  const lines: string[] = [`name: ${caller.name}`, ""];

  // The generated-file marker. `sync` reads it to tell a file it wrote from one a
  // human has taken over, and it names the command to re-run rather than implying the
  // file must not be touched — editing the `with:` inputs is the intended use.
  lines.push("# Generated by `agent-workflows init`. Safe to edit: `sync` only ever");
  lines.push("# updates the `uses:` ref below and reports anything else that drifted.");
  lines.push("#");
  for (const line of caller.blurb) lines.push(line === "" ? "#" : `# ${line}`);
  lines.push(...onBlock(caller));
  lines.push("");
  lines.push("permissions:");
  for (const [scope, level] of Object.entries(caller.permissions)) {
    lines.push(`  ${scope}: ${level}`);
  }
  lines.push("");
  lines.push("jobs:");
  lines.push(`  ${caller.job}:`);
  lines.push(...ifGuard(caller, options.publicRepo));
  lines.push(`    uses: ${usesRef(caller, options.workflowsRepo, options.ref)}`);
  lines.push("    with:");
  for (const [key, value] of Object.entries(caller.with ?? {})) {
    lines.push(`      ${key}: ${value}`);
  }
  // The orchestrator installs no toolchain (it runs no agent), so `enable-ruby` is
  // not one of its inputs and passing it would fail the workflow call.
  if (caller.toolchain) lines.push(`      enable-ruby: ${options.enableRuby}`);
  lines.push(`      git-author-email: ${options.gitAuthorEmail}`);
  lines.push("    secrets: inherit");

  return `${lines.join("\n")}\n`;
}

export interface Repin {
  // The file with its ref rewritten, or the original when nothing matched.
  readonly content: string;
  // What the file pointed at before. Null when no `uses:` into the central repo was
  // found at all — a caller pointing somewhere else entirely, which `sync` reports
  // rather than rewrites.
  readonly from: string | null;
}

// Move an existing caller's pin to `ref`, touching nothing else.
//
// Matched on the `uses:` path INTO the given workflows repo, so a caller that also
// uses third-party actions (a setup step, a notifier) keeps their pins — only the
// line pointing at the central workflow moves.
export function repinCaller(content: string, workflowsRepo: string, ref: string): Repin {
  const pattern = new RegExp(
    `(uses:\\s*${escapeRegExp(workflowsRepo)}/\\.github/workflows/[\\w.-]+)@(\\S+)`,
  );
  const match = pattern.exec(content);
  if (!match) return { content, from: null };
  return { content: content.replace(pattern, `$1@${ref}`), from: match[2] };
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// Every caller file a selection of verbs implies, rendered.
export function renderCallers(
  verbs: readonly Verb[],
  options: CallerOptions,
): ReadonlyArray<{ readonly file: string; readonly content: string }> {
  return callersFor(verbs).map((caller) => ({
    file: caller.file,
    content: renderCaller(caller, options),
  }));
}
